print("Hello, let's get to know about you before we begin generating passport for you!")
name = input("Firstly, what's your name?\n>>")
class_of_hero = input("And the class you belong to:(e.g., Wizard, Rogue, Barbarian)\n>>")
hometown = input("Where are you from? (Your hometown)\n>>")
p_q_i = input("How about your primary quest item?\n>>")
nemesis = input("What is the name of Nemesis?\n>>")

print('\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print("  KINGDOM OF CODERRA - ADVENTURER'S PASSPORT")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")
print(f"Name:      [{name}]")
print(f"Class:     [{class_of_hero}]")
print(f"Origin:    [{hometown}]\n")
print(f"Known Alias: The [{hometown}] [{class_of_hero}]\n")

print("----------------------------------------")
print("CURRENT MISSION:")
print(f"Retrieve the [{p_q_i}] from the clutches of [{nemesis}]!\n\n\n\n")
